### ISSUE TITLE
古いドキュメントであることの警告を表示

### ISSUE THREAD

**Issue by munierujp** [vuejs-jp/012-jp.vuejs.org#2]
たとえば「vue ディレクティブ」のようにGoogle検索したときなど、 012-jp.vuejs.org のページが検索結果に表示されることがありますが、開いてもドキュメントが古いものであることがわかりません。
ページ上部に警告メッセージを表示するなどして、閲覧者に古いドキュメントを参照していることを示したほうがいいかと思います。

**Comment by kazupon** [comment]
ありがとうございます！こちらどこかのタイミングで header あたりに注意メッセージ入れる等、で対応したいと思います。

**Comment by tnir** [comment]
古いドキュメントへの参照が数年経っても一向に解消しないので、 #3 を作りました。
